name: Go CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest  # Windows runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Cache Go modules
      if: contains(hashFiles('go.mod'), '')  # Only cache if go.mod exists
      uses: actions/cache@v3
      with:
        path: |
            ~\go\bin
            ~\go\pkg\mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
        
    - name: Build
      run: go build ./...
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Verify formatting
      run: |
        gofmt -d .
        gofmt -l . | tee fmt.out
        if [[ -s fmt.out ]]; then exit 1; fi