name: Go CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true  # Uses built-in Go caching
    
    - name: Build
      run: |
        cd cmd/server  # Change to your main package directory
        go build -v
        
    - name: Test
      run: |
        cd internal/shortener  # Change to your test directory
        go test -v