name: Go CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Build
      run: go build -v

    - name: Test
      shell: cmd
      run: |
        if exist *_test.go (
          go test -v
        ) else (
          echo No tests found
        )