name: Go CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest  # Windows runner
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - run: go build ./...
      - run: go test -v ./...