name: Go CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true  # This is the key change - uses built-in Go caching
    
    - name: Build
      run: go build ./...
    
    - name: Test
      run: go test -v ./...